steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'bash'
    args: ['rm', '-r', 'src']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - image_builder
      - --trigger-http
      - --allow-unauthenticated
      - --runtime=nodejs14
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'
